### PR TITLE
Colonelpanic8 changes together

### PR DESCRIPTION
**Pull request by colonelpanic8**
#78 #77 #76 #74 #73 with conflicts resolved, just in case you want to take them all.

### CODE REVIEW

**Comment by akhramov** [comment]
:see_no_evil: hope this doesn't break doom this time.

**Comment by colonelpanic8** [comment]
> 🙈 hope this doesn't break doom this time.

oh... there's a lot of changes in here. very possible.

I wonder if it might have been better to have the individual commits in the history. Seems like some squashing is enabled when you do merges. Oh well...

**Comment by akhramov** [comment]
Sure, do what you want. I don't use the package, so for me it made perfect sense to give the push bit to someone who cares.

**Comment by colonelpanic8** [comment]
> Sure, do what you want. I don't use the package, so for me it made perfect sense to give the push bit to someone who cares.

Ah okay. Awesome, I think I can do a good job with this!

**Pull request merged**
