### PR TITLE
Fix org widening when narrowed on a subtree

### PR DESCRIPTION
**Pull request by neeasade**
solution stolen from: https://github.com/spegoraro/org-alert/pull/10/files
issue reported in: https://github.com/akhramov/org-wild-notifier.el/issues/10#issuecomment-412193468

### CODE REVIEW

**Comment by neeasade** [comment]
to be fair, I have not been able to get this package to send any alerts in the first place though

**Comment by neeasade** [comment]
^ the above comment was PEBKAC, this pr does work 👍

**Comment by akhramov** [comment]
Thanks!

**Comment by codygman** [comment]
Awesome! I can't wait to try this @akhramov !

**Comment by codygman** [comment]
@akhramov @neeasade This works as far as not messing up indirect buffers, but I navigation in org buffers still seems to be broken.

**Pull request merged**
